name: Windows Installer Test
on:
  workflow_run:
    workflows: ["Windows xTB Installer"]
    types:
      - completed

jobs:
  install-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    steps:
      - name: Download installer artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: avogadro-windows-xtb-installer
          path: installer
      - name: Install Avogadro
        shell: pwsh
        run: |
          $exe = Get-ChildItem installer\*.exe | Select-Object -First 1
          & $exe /S
      - name: List install directory
        shell: cmd
        run: |
          tree /f "C:\Program Files (x86)\Avogadro"
